---
version: 2
builds:
  - main: .
    binary: hulak
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/xaaha/hulak/pkg/userFlags.version={{.Version}}
archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - man/hulak.1
    name_template: '{{ .ProjectName }}_ {{- .Version }}_ {{- title .Os }}_ {{- if eq .Arch "amd64" }}x86_64 {{- else }}{{ .Arch }}{{ end }}'
checksum:
  name_template: checksums.txt
homebrew_casks:
  - repository:
      owner: xaaha
      name: homebrew-tap
      token: "{{ .Env.GH_PAT }}"
    homepage: https://github.com/xaaha/hulak
    description: File based API client for terminal nerds
    license: MIT
    binaries:
      - hulak
    manpages:
      - man/hulak.1
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hulak"]
          end
    caveats: |
      The binary is not signed or notarized. macOS quarantine has been automatically removed.
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
