// Generates zsh and bash shell completion from the live command tree.
// Source of truth: the command tree (subcommands, aliases, flags) plus two
// per-command annotations — argDef.Kind for positional value completion and
// pathFlagNames (in command.go) for flag-value completion. New commands and
// flags appear automatically; only path/yaml hints need declaration.
package userflags

import (
	"flag"
	"fmt"
	"io"
	"os"
	"sort"
	"strings"

	"github.com/xaaha/hulak/pkg/utils"
)

// newCompletionCmd prints a shell completion script to stdout. Use it when
// installing via `go install`, where there's no package manager to drop the
// script in the right path. Homebrew users don't need this — the cask
// installs completions directly.
func newCompletionCmd() *command {
	zsh := &command{
		Name:  "zsh",
		Short: "Print the zsh completion script",
		Long: "Print the zsh completion script to stdout.\n\n" +
			"Install with:\n" +
			"  hulak completion zsh > \"${fpath[1]}/_hulak\"\n" +
			"Then restart your shell. Requires `autoload -Uz compinit && compinit` in your zshrc.",
		Run: func(_ []string) error { generateZshCompletion(os.Stdout); return nil },
	}
	bash := &command{
		Name:  "bash",
		Short: "Print the bash completion script",
		Long: "Print the bash completion script to stdout.\n\n" +
			"Install with (macOS, Homebrew bash-completion):\n" +
			"  hulak completion bash > $(brew --prefix)/etc/bash_completion.d/hulak\n" +
			"Linux:\n" +
			"  hulak completion bash | sudo tee /etc/bash_completion.d/hulak >/dev/null",
		Run: func(_ []string) error { generateBashCompletion(os.Stdout); return nil },
	}
	return &command{
		Name:  "completion",
		Short: "Print a shell completion script (for go-install users)",
		Long: "Print a completion script for the given shell.\n\n" +
			"Homebrew users don't need this — the cask installs completions directly.\n" +
			"For `go install` users, redirect the output into a directory your shell\n" +
			"already scans for completions.",
		Examples: []*utils.CommandHelp{
			{
				Command:     "hulak completion zsh > \"${fpath[1]}/_hulak\"",
				Description: "zsh (any platform; restart shell after)",
			},
			{
				Command:     "hulak completion bash > $(brew --prefix)/etc/bash_completion.d/hulak",
				Description: "bash on macOS (Homebrew bash-completion)",
			},
			{
				Command:     "hulak completion bash | sudo tee /etc/bash_completion.d/hulak >/dev/null",
				Description: "bash on Linux (system bash-completion)",
			},
		},
		SubCommands: []*command{bash, zsh},
	}
}

// --- shared helpers ---

func allNames(cmd *command) []string {
	return append([]string{cmd.Name}, cmd.Aliases...)
}

func dashed(name string) string {
	if len(name) == 1 {
		return "-" + name
	}
	return "--" + name
}

// argKind returns the completion kind for the first positional ("yaml",
// "file", or "" for none). Commands with no Args have nothing to complete.
func argKind(cmd *command) string {
	if len(cmd.Args) == 0 {
		return ""
	}
	return cmd.Args[0].Kind
}

func zshFn(name string) string { return strings.ReplaceAll(name, "-", "_") }

// --- zsh ---

func generateZshCompletion(w io.Writer) {
	p := func(format string, a ...any) { fmt.Fprintf(w, format+"\n", a...) }
	p("#compdef hulak")
	p("# Generated by 'hulak gendocs' — do not edit by hand.")
	p("")
	emitZshCmd(p, subCommands(), "_hulak")
	p("_hulak_envs() {")
	p("  [[ -d env ]] || return")
	p("  local -a envs=(${(f)\"$(cd env && for f in *.env(N); do print -- \"${f%%.env}\"; done)\"})")
	p("  (( ${#envs} )) && _describe -t envs 'environment' envs")
	p("}")
	p("")
	p("compdef _hulak hulak")
}

// emitZshCmd writes the completer for cmd and recurses into its visible
// subcommands. Function name carries the path (e.g. _hulak_secrets_set).
// Leaf commands with nothing to complete emit no function and no dispatch.
func emitZshCmd(p func(string, ...any), cmd *command, fn string) {
	subs := cmd.visibleSubs()
	specs := zshFlagSpecs(cmd)

	if len(subs) == 0 {
		if pos := zshPositionalSpec(cmd); pos != "" {
			specs = append(specs, pos)
		}
		if len(specs) == 0 {
			return // nothing to complete — skip the function entirely
		}
		emitZshArgs(p, fn, specs)
		return
	}

	var dispatchSubs []*command
	for _, sub := range subs {
		if zshSubHasCompleter(sub) {
			dispatchSubs = append(dispatchSubs, sub)
		}
	}

	p("%s() {", fn)
	if len(dispatchSubs) == 0 {
		// No sub needs further dispatch — single-pass _arguments is enough.
		p("  _arguments \\")
		for _, s := range specs {
			p("    %s \\", s)
		}
		p("    '1: :%s_subs'", fn)
		p("}")
		p("")
	} else {
		p("  local state ret=1")
		p("  _arguments -C \\")
		for _, s := range specs {
			p("    %s \\", s)
		}
		p("    '1: :%s_subs' \\", fn)
		p("    '*::arg:->args' && ret=0")
		p("  [[ $state == args ]] && case $words[1] in")
		for _, sub := range dispatchSubs {
			p("    %s) %s_%s && ret=0 ;;", strings.Join(allNames(sub), "|"), fn, zshFn(sub.Name))
		}
		p("  esac")
		p("  return ret")
		p("}")
		p("")
	}

	p("%s_subs() {", fn)
	p("  local -a subs=(")
	for _, sub := range subs {
		for _, name := range allNames(sub) {
			p("    %s", zshDesc(name, sub.Short))
		}
	}
	p("  )")
	p("  _describe -t commands '%s subcommand' subs", cmd.Name)
	p("}")
	p("")

	for _, sub := range subs {
		emitZshCmd(p, sub, fn+"_"+zshFn(sub.Name))
	}
}

// zshSubHasCompleter reports whether emitZshCmd would emit a function for
// sub. Used to skip dispatch lines that would call into nothing.
func zshSubHasCompleter(sub *command) bool {
	if len(sub.visibleSubs()) > 0 {
		return true
	}
	return len(zshFlagSpecs(sub)) > 0 || zshPositionalSpec(sub) != ""
}

func emitZshArgs(p func(string, ...any), fn string, specs []string) {
	p("%s() {", fn)
	p("  _arguments \\")
	for i, s := range specs {
		tail := " \\"
		if i == len(specs)-1 {
			tail = ""
		}
		p("    %s%s", s, tail)
	}
	p("}")
	p("")
}

func zshPositionalSpec(cmd *command) string {
	switch argKind(cmd) {
	case "yaml":
		return `'*:file or directory:_files -g "*.(yaml|yml|hk.yaml|hk.yml)"'`
	case "file":
		return "'*:file:_files'"
	}
	return ""
}

// zshFlagSpecs returns one `_arguments` spec per visible flag. Aliased
// pairs (per flagAliases) merge into a single mutex spec like
// `(-o --out){-o,--out}'[desc]:path:_files'`.
func zshFlagSpecs(cmd *command) []string {
	if cmd.Flags == nil {
		return nil
	}

	type spec struct {
		forms   []string
		usage   string
		isBool  bool
		valKind string // "env" | "path" | ""
	}
	specs := map[string]*spec{}
	var order []string

	longFor := flagPairings(cmd.Flags)
	visitVisibleFlags(cmd.Flags, func(f *flag.Flag) {
		s := &spec{
			usage:   f.Usage,
			isBool:  f.DefValue == "true" || f.DefValue == "false",
			forms:   []string{dashed(f.Name)},
			valKind: flagValueKind(f.Name),
		}
		if long, ok := longFor[f.Name]; ok {
			s.forms = append(s.forms, dashed(long))
			if kind := flagValueKind(long); kind != "" && s.valKind == "" {
				s.valKind = kind
			}
		}
		sort.Strings(s.forms)
		specs[f.Name] = s
		order = append(order, f.Name)
	})
	sort.Strings(order)

	out := make([]string, 0, len(order))
	for _, name := range order {
		s := specs[name]
		desc := "[" + zshEscBracket(s.usage) + "]"
		action := zshAction(s.isBool, s.valKind)
		if len(s.forms) > 1 {
			out = append(out, fmt.Sprintf("'(%s)'{%s}'%s%s'",
				strings.Join(s.forms, " "), strings.Join(s.forms, ","), desc, action))
		} else {
			out = append(out, fmt.Sprintf("'%s%s%s'", s.forms[0], desc, action))
		}
	}
	return out
}

// flagValueKind returns "env", "path", or "" based on the flag name.
// Env flags are detected by name (registerEnvFlag enforces the convention).
// Path flags come from the explicit pathFlagNames allowlist.
func flagValueKind(name string) string {
	if name == "env" || name == "environment" {
		return "env"
	}
	if pathFlagNames[name] {
		return "path"
	}
	return ""
}

func zshAction(isBool bool, valKind string) string {
	if isBool {
		return ""
	}
	switch valKind {
	case "env":
		return ":env:_hulak_envs"
	case "path":
		return ":path:_files"
	}
	return ":value:"
}

func zshDesc(name, short string) string {
	first, _, _ := strings.Cut(short, "\n")
	first = strings.ReplaceAll(first, "'", `'\''`)
	first = strings.ReplaceAll(first, ":", `\:`)
	return fmt.Sprintf("'%s:%s'", name, first)
}

func zshEscBracket(s string) string {
	first, _, _ := strings.Cut(s, "\n")
	for _, pair := range [][2]string{
		{"\\", `\\`}, {"'", `'\''`}, {"[", `\[`}, {"]", `\]`}, {":", `\:`},
	} {
		first = strings.ReplaceAll(first, pair[0], pair[1])
	}
	return first
}

// --- bash ---

// bashCtx is the data the bash chain walker needs at runtime: every valid
// alias-expanded chain ("hulak:secrets:set"), and which flags consume a
// value (so the walker skips that value when chaining). Collected once so
// the generated script doesn't re-walk the tree on every tab press.
type bashCtx struct {
	validPaths []string        // alias-expanded chains
	valueFlags map[string]bool // dashed names that consume the next word
	envFlags   map[string]bool // subset whose value completes env names
	pathFlags  map[string]bool // subset whose value completes a filesystem path
}

func collectBashCtx(root *command) bashCtx {
	ctx := bashCtx{
		valueFlags: map[string]bool{},
		envFlags:   map[string]bool{},
		pathFlags:  map[string]bool{},
	}
	addForm := func(set map[string]bool, name string) {
		set["-"+name] = true
		if len(name) > 1 {
			set["--"+name] = true
		}
	}
	var walk func(cmd *command, patterns []string)
	walk = func(cmd *command, patterns []string) {
		ctx.validPaths = append(ctx.validPaths, patterns...)
		if cmd.Flags != nil {
			cmd.Flags.VisitAll(func(f *flag.Flag) {
				if hiddenFlags[f.Name] || f.DefValue == "true" || f.DefValue == "false" {
					return
				}
				addForm(ctx.valueFlags, f.Name)
				switch flagValueKind(f.Name) {
				case "env":
					addForm(ctx.envFlags, f.Name)
				case "path":
					addForm(ctx.pathFlags, f.Name)
				}
			})
		}
		for _, sub := range cmd.visibleSubs() {
			next := make([]string, 0, len(patterns)*len(allNames(sub)))
			for _, base := range patterns {
				for _, name := range allNames(sub) {
					next = append(next, base+":"+name)
				}
			}
			walk(sub, next)
		}
	}
	walk(root, []string{"hulak"})
	sort.Strings(ctx.validPaths)
	return ctx
}

func sortedKeys(m map[string]bool) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

func generateBashCompletion(w io.Writer) {
	p := func(format string, a ...any) { fmt.Fprintf(w, format+"\n", a...) }
	root := subCommands()
	ctx := collectBashCtx(root)

	p("# bash completion for hulak")
	p("# Generated by 'hulak gendocs' — do not edit by hand.")
	p("")
	p("_hulak_envs() {")
	p("  [[ -d env ]] || return 0")
	p("  local f")
	p("  for f in env/*.env; do [[ -e $f ]] || continue; f=${f##*/}; printf '%%s\\n' \"${f%%.env}\"; done")
	p("}")
	p("")
	// Path completion that handles filenames with spaces: read compgen
	// output one line at a time instead of word-splitting on $(...).
	// `compopt -o filenames` asks bash to quote and append slashes correctly.
	p("_hulak_path_files() {")
	p("  local cur=$1 f")
	p("  COMPREPLY=()")
	p("  while IFS= read -r f; do [[ -n $f ]] && COMPREPLY+=(\"$f\"); done < <(compgen -f -- \"$cur\")")
	p("  compopt -o filenames 2>/dev/null")
	p("}")
	p("")
	// Yaml-only file completion uses a case-pattern filter so we don't need
	// `shopt -s extglob` enabled in the user's shell.
	p("_hulak_yaml_files() {")
	p("  local cur=$1 f")
	p("  COMPREPLY=()")
	p("  while IFS= read -r f; do")
	p("    case \"$f\" in *.yaml|*.yml|*.hk.yaml|*.hk.yml) COMPREPLY+=(\"$f\") ;; esac")
	p("  done < <(compgen -f -- \"$cur\")")
	p("  while IFS= read -r f; do [[ -n $f ]] && COMPREPLY+=(\"$f\"); done < <(compgen -d -- \"$cur\")")
	p("  compopt -o filenames 2>/dev/null")
	p("}")
	p("")
	p("_hulak_takes_value() {")
	p("  case \"$1\" in")
	p("    %s) return 0 ;;", strings.Join(sortedKeys(ctx.valueFlags), "|"))
	p("  esac")
	p("  return 1")
	p("}")
	p("")
	envForms := sortedKeys(ctx.envFlags)
	pathForms := sortedKeys(ctx.pathFlags)
	p("_hulak_complete_value() {")
	p("  case \"$1\" in")
	if len(envForms) > 0 {
		p("    %s) COMPREPLY=( $(compgen -W \"$(_hulak_envs)\" -- \"$2\") ) ;;", strings.Join(envForms, "|"))
	}
	if len(pathForms) > 0 {
		p("    %s) _hulak_path_files \"$2\" ;;", strings.Join(pathForms, "|"))
	}
	p("    *) COMPREPLY=() ;;")
	p("  esac")
	p("}")
	p("")
	p("_hulak_is_path() {")
	p("  case \"$1\" in")
	p("    %s) return 0 ;;", strings.Join(ctx.validPaths, "|"))
	p("  esac")
	p("  return 1")
	p("}")
	p("")
	p("_hulak() {")
	p("  local cur=\"${COMP_WORDS[COMP_CWORD]}\" prev=\"${COMP_WORDS[COMP_CWORD-1]}\" chain=hulak i=1")
	p("  if _hulak_takes_value \"$prev\"; then _hulak_complete_value \"$prev\" \"$cur\"; return; fi")
	p("  while (( i < COMP_CWORD )); do")
	p("    local w=\"${COMP_WORDS[i]}\"")
	p("    if [[ -z $w ]]; then ((i++)); continue; fi")
	p("    if [[ $w == -* ]]; then")
	p("      _hulak_takes_value \"$w\" && ((i++))")
	p("      ((i++)); continue")
	p("    fi")
	p("    if _hulak_is_path \"$chain:$w\"; then chain+=:$w; ((i++)); else break; fi")
	p("  done")
	p("  case \"$chain\" in")
	bashEmitCases(p, root, []string{"hulak"})
	p("    *) COMPREPLY=() ;;")
	p("  esac")
	p("}")
	p("")
	p("complete -F _hulak hulak")
}

// bashEmitCases walks the tree emitting one case clause per visible command
// path. patterns is every alias-expanded path leading to cmd; extended as
// we recurse so we never re-resolve aliases.
func bashEmitCases(p func(string, ...any), cmd *command, patterns []string) {
	subs := cmd.visibleSubs()
	var sugg []string
	for _, sub := range subs {
		sugg = append(sugg, allNames(sub)...)
	}
	if cmd.Flags != nil {
		cmd.Flags.VisitAll(func(f *flag.Flag) {
			if !hiddenFlags[f.Name] {
				sugg = append(sugg, dashed(f.Name))
			}
		})
	}
	sort.Strings(sugg)

	if len(sugg) > 0 {
		p("    %s)", strings.Join(patterns, "|"))
		switch {
		case argKind(cmd) == "yaml":
			p("      if [[ $cur == -* ]]; then COMPREPLY=( $(compgen -W %q -- \"$cur\") )", strings.Join(sugg, " "))
			p("      else _hulak_yaml_files \"$cur\"; fi")
		case argKind(cmd) == "file":
			p("      if [[ $cur == -* ]]; then COMPREPLY=( $(compgen -W %q -- \"$cur\") )", strings.Join(sugg, " "))
			p("      else _hulak_path_files \"$cur\"; fi")
		default:
			p("      COMPREPLY=( $(compgen -W %q -- \"$cur\") )", strings.Join(sugg, " "))
		}
		p("      ;;")
	}

	for _, sub := range subs {
		next := make([]string, 0, len(patterns)*len(allNames(sub)))
		for _, base := range patterns {
			for _, name := range allNames(sub) {
				next = append(next, base+":"+name)
			}
		}
		bashEmitCases(p, sub, next)
	}
}
