#compdef hulak
# Generated by 'hulak gendocs' — do not edit by hand.

_hulak() {
  local state ret=1
  _arguments -C \
    '--debug[Enable debug mode for full request/response details]' \
    '--dir[Directory path to run concurrently]:path:_files' \
    '--dirseq[Directory path to run in alphabetical order]:path:_files' \
    '--dry-run[Print the built request and exit without sending it]' \
    '(--env --environment)'{--env,--environment}'[Environment to use (omit to pick interactively)]:env:_hulak_envs' \
    '(--file -f)'{--file,-f}'[File name for making an API request (case-insensitive)]:path:_files' \
    '(--file-path --fp)'{--file-path,--fp}'[Relative (or absolute) file path of the request file]:path:_files' \
    '(--quiet -q)'{--quiet,-q}'[Suppress the end-of-run summary table]' \
    '--show[Reveal sensitive headers (Authorization, Cookie, etc.) in --dry-run output]' \
    '--timeout[Per-request timeout, e.g. 5m or 90s (default 60s)]:value:' \
    '1: :_hulak_subs' \
    '*::arg:->args' && ret=0
  [[ $state == args ]] && case $words[1] in
    run) _hulak_run && ret=0 ;;
    init) _hulak_init && ret=0 ;;
    example) _hulak_example && ret=0 ;;
    migrate) _hulak_migrate && ret=0 ;;
    completion) _hulak_completion && ret=0 ;;
    doctor) _hulak_doctor && ret=0 ;;
    gql|graphql) _hulak_gql && ret=0 ;;
    mcp) _hulak_mcp && ret=0 ;;
    secrets|env) _hulak_secrets && ret=0 ;;
  esac
  return ret
}

_hulak_subs() {
  local -a subs=(
    'run:Run API request file(s) or directory'
    'version:Print hulak version'
    'init:Initialize a hulak project'
    'example:Scaffold an example request file'
    'migrate:Migrate Postman collections to hulak format'
    'completion:Print a shell completion script (for go-install users)'
    'doctor:Check project health'
    'gql:Open the GraphQL explorer'
    'graphql:Open the GraphQL explorer'
    'mcp:Serve requests to AI agents over MCP'
    'secrets:Manage encrypted environment secrets'
    'env:Manage encrypted environment secrets'
    'help:Show help for hulak'
  )
  _describe -t commands 'hulak subcommand' subs
}

_hulak_run() {
  _arguments \
    '--debug[Enable debug mode]' \
    '--dry-run[Print the built request and exit without sending it]' \
    '(--env --environment)'{--env,--environment}'[Environment to use]:env:_hulak_envs' \
    '(--quiet -q)'{--quiet,-q}'[Suppress the end-of-run summary table]' \
    '(--seq --sequential)'{--seq,--sequential}'[Run directory files sequentially]' \
    '--show[Reveal sensitive headers (Authorization, Cookie, etc.) in --dry-run output]' \
    '--ssh-identity[Path to SSH private key for vault decryption]:path:_files' \
    '--timeout[Per-request timeout, e.g. 5m or 90s (default 60s)]:value:' \
    '*:file or directory:_files -g "*.(yaml|yml|hk.yaml|hk.yml)"'
}

_hulak_init() {
  local state ret=1
  _arguments -C \
    '--env[Create specific environment files instead of the default setup]' \
    '--ssh[Use SSH ed25519 key (~/.ssh/id_ed25519) instead of generating an age keypair]' \
    '--ssh-identity[Path to SSH private key (implies --ssh; overrides the default path)]:path:_files' \
    '1: :_hulak_init_subs' \
    '*::arg:->args' && ret=0
  [[ $state == args ]] && case $words[1] in
    classic|plain|no-vault) _hulak_init_classic && ret=0 ;;
  esac
  return ret
}

_hulak_init_subs() {
  local -a subs=(
    'classic:Initialize with the plaintext env/ layout'
    'plain:Initialize with the plaintext env/ layout'
    'no-vault:Initialize with the plaintext env/ layout'
  )
  _describe -t commands 'init subcommand' subs
}

_hulak_init_classic() {
  _arguments \
    '--env[Create specific environment files instead of the default setup]'
}

_hulak_example() {
  _arguments \
    '(--out -o)'{--out,-o}'[Output path. Directory (ends with '\''/'\'' or no .yaml/.yml extension) → file lands inside with the canonical name; otherwise treated as a full file path. Parent directories are created.]:path:_files'
}

_hulak_migrate() {
  _arguments \
    '*:file:_files'
}

_hulak_completion() {
  _arguments \
    '1: :_hulak_completion_subs'
}

_hulak_completion_subs() {
  local -a subs=(
    'bash:Print the bash completion script'
    'zsh:Print the zsh completion script'
  )
  _describe -t commands 'completion subcommand' subs
}

_hulak_doctor() {
  _arguments \
    '--fix[Auto-repair safe issues (chmod, .gitignore)]' \
    '--json[Output findings as JSON to stdout]' \
    '--yes[Skip confirmation prompts (use with --fix)]'
}

_hulak_gql() {
  _arguments \
    '(--env --environment)'{--env,--environment}'[Environment to use (skips interactive selector)]:env:_hulak_envs' \
    '*:file or directory:_files -g "*.(yaml|yml|hk.yaml|hk.yml)"'
}

_hulak_mcp() {
  _arguments \
    '--default-project[Project assumed when a request name is unambiguous but no project is given]:value:' \
    '--project[Named project as name=path (repeatable, e.g. api=~/work/api-tests)]:value:'
}

_hulak_secrets() {
  local state ret=1
  _arguments -C \
    '1: :_hulak_secrets_subs' \
    '*::arg:->args' && ret=0
  [[ $state == args ]] && case $words[1] in
    create) _hulak_secrets_create && ret=0 ;;
    delete|rm) _hulak_secrets_delete && ret=0 ;;
    keys|key) _hulak_secrets_keys && ret=0 ;;
    edit) _hulak_secrets_edit && ret=0 ;;
    identity) _hulak_secrets_identity && ret=0 ;;
    backup) _hulak_secrets_backup && ret=0 ;;
    restore) _hulak_secrets_restore && ret=0 ;;
  esac
  return ret
}

_hulak_secrets_subs() {
  local -a subs=(
    'create:Create a new empty environment'
    'delete:Delete an environment'
    'rm:Delete an environment'
    'list:List environment names'
    'ls:List environment names'
    'keys:Manage keys within an environment'
    'key:Manage keys within an environment'
    'edit:Edit secrets interactively'
    'identity:Manage age identities and recipients'
    'rename:Rename an environment (unix-style mv)'
    'mv:Rename an environment (unix-style mv)'
    'sync:Re-encrypt the store to current recipients'
    'migrate:Migrate env/*.env files to the encrypted vault'
    'backup:Create a backup of the encrypted store'
    'restore:Restore the encrypted store from a backup'
  )
  _describe -t commands 'secrets subcommand' subs
}

_hulak_secrets_create() {
  _arguments \
    '(--env --environment)'{--env,--environment}'[Name of the new environment to create (required)]:env:_hulak_envs'
}

_hulak_secrets_delete() {
  _arguments \
    '(--env --environment)'{--env,--environment}'[Environment to delete (omit to pick interactively)]:env:_hulak_envs' \
    '-y[Skip the destructive confirm prompt]' \
    '--yes[Skip the destructive confirm prompt]'
}

_hulak_secrets_keys() {
  local state ret=1
  _arguments -C \
    '(--env --environment)'{--env,--environment}'[Environment to operate on]:env:_hulak_envs' \
    '--search[Filter keys by case-insensitive substring or glob pattern]:value:' \
    '--show[Reveal values instead of masking them]' \
    '1: :_hulak_secrets_keys_subs' \
    '*::arg:->args' && ret=0
  [[ $state == args ]] && case $words[1] in
    list|ls) _hulak_secrets_keys_list && ret=0 ;;
    set|add) _hulak_secrets_keys_set && ret=0 ;;
    get) _hulak_secrets_keys_get && ret=0 ;;
    delete|rm) _hulak_secrets_keys_delete && ret=0 ;;
  esac
  return ret
}

_hulak_secrets_keys_subs() {
  local -a subs=(
    'list:List keys in an environment'
    'ls:List keys in an environment'
    'set:Set a key-value pair'
    'add:Set a key-value pair'
    'get:Get a value by key'
    'delete:Delete a key from an environment'
    'rm:Delete a key from an environment'
  )
  _describe -t commands 'keys subcommand' subs
}

_hulak_secrets_keys_list() {
  _arguments \
    '(--env --environment)'{--env,--environment}'[Environment to operate on]:env:_hulak_envs' \
    '--search[Filter keys by case-insensitive substring or glob pattern]:value:' \
    '--show[Reveal values instead of masking them]'
}

_hulak_secrets_keys_set() {
  _arguments \
    '(--env --environment)'{--env,--environment}'[Environment to operate on]:env:_hulak_envs' \
    '--stdin[Read value from stdin]' \
    '(--type -t)'{--type,-t}'[Value type\: string|int|float|bool|json]:value:'
}

_hulak_secrets_keys_get() {
  _arguments \
    '(--env --environment)'{--env,--environment}'[Environment to operate on]:env:_hulak_envs'
}

_hulak_secrets_keys_delete() {
  _arguments \
    '(--env --environment)'{--env,--environment}'[Environment to operate on]:env:_hulak_envs'
}

_hulak_secrets_edit() {
  _arguments \
    '(--env --environment)'{--env,--environment}'[Environment to edit (omit to pick interactively)]:env:_hulak_envs'
}

_hulak_secrets_identity() {
  local state ret=1
  _arguments -C \
    '1: :_hulak_secrets_identity_subs' \
    '*::arg:->args' && ret=0
  [[ $state == args ]] && case $words[1] in
    add-recipient) _hulak_secrets_identity_add_recipient && ret=0 ;;
    export) _hulak_secrets_identity_export && ret=0 ;;
    generate|gen) _hulak_secrets_identity_generate && ret=0 ;;
    import) _hulak_secrets_identity_import && ret=0 ;;
  esac
  return ret
}

_hulak_secrets_identity_subs() {
  local -a subs=(
    'add-recipient:Add a recipient for shared vault access'
    'export:Export the age identity (private key)'
    'generate:Generate a new age keypair without creating a vault'
    'gen:Generate a new age keypair without creating a vault'
    'import:Import an age identity (private key)'
    'list:List identities that can decrypt the vault'
    'ls:List identities that can decrypt the vault'
    'list-recipients:List all recipients'
    'remove-recipient:Remove a recipient'
    'rotate:Rotate your age identity (keypair)'
  )
  _describe -t commands 'identity subcommand' subs
}

_hulak_secrets_identity_add_recipient() {
  _arguments \
    '--allow-rsa[Also accept ssh-rsa keys (lower security margin)]' \
    '--github[Fetch ed25519 keys from GitHub (username)]:value:' \
    '--keyserver[Base URL of keyserver (e.g. https\://gitlab.com)]:value:' \
    '--name[Human-readable label for the recipient (defaults to OS username)]:value:' \
    '--stdin[Read keys from stdin (one per line)]'
}

_hulak_secrets_identity_export() {
  _arguments \
    '(--out -o)'{--out,-o}'[Write key to file instead of stdout (mode 0600). Directory inputs append '\''identity.txt'\''.]:path:_files'
}

_hulak_secrets_identity_generate() {
  _arguments \
    '--name[Auto-register the new key as a recipient with this label (requires an existing decrypt path; defaults label to OS username)]:value:'
}

_hulak_secrets_identity_import() {
  _arguments \
    '--force[Overwrite existing identity file]' \
    '--name[Auto-register the imported key as a recipient with this label (requires an existing decrypt path; defaults label to OS username)]:value:' \
    '--stdin[Read key from stdin]' \
    '*:file:_files'
}

_hulak_secrets_backup() {
  _arguments \
    '-f[Overwrite existing --out target]' \
    '--force[Overwrite existing --out target]' \
    '(--out -o)'{--out,-o}'[Custom output path for the backup file. Directory inputs append a timestamped name.]:path:_files' \
    '1: :_hulak_secrets_backup_subs'
}

_hulak_secrets_backup_subs() {
  local -a subs=(
    'list:List existing backups'
    'ls:List existing backups'
  )
  _describe -t commands 'backup subcommand' subs
}

_hulak_secrets_restore() {
  _arguments \
    '-f[Skip confirmation prompt]' \
    '--force[Skip confirmation prompt]' \
    '*:file:_files'
}

_hulak_envs() {
  [[ -d env ]] || return
  local -a envs=(${(f)"$(cd env && for f in *.env(N); do print -- "${f%.env}"; done)"})
  (( ${#envs} )) && _describe -t envs 'environment' envs
}

compdef _hulak hulak
