# bash completion for hulak
# Generated by 'hulak gendocs' — do not edit by hand.

_hulak_envs() {
  [[ -d env ]] || return 0
  local f
  for f in env/*.env; do [[ -e $f ]] || continue; f=${f##*/}; printf '%s\n' "${f%.env}"; done
}

_hulak_path_files() {
  local cur=$1 f
  COMPREPLY=()
  while IFS= read -r f; do [[ -n $f ]] && COMPREPLY+=("$f"); done < <(compgen -f -- "$cur")
  compopt -o filenames 2>/dev/null
}

_hulak_yaml_files() {
  local cur=$1 f
  COMPREPLY=()
  while IFS= read -r f; do
    case "$f" in *.yaml|*.yml|*.hk.yaml|*.hk.yml) COMPREPLY+=("$f") ;; esac
  done < <(compgen -f -- "$cur")
  while IFS= read -r f; do [[ -n $f ]] && COMPREPLY+=("$f"); done < <(compgen -d -- "$cur")
  compopt -o filenames 2>/dev/null
}

_hulak_takes_value() {
  case "$1" in
    --dir|--dirseq|--env|--environment|--file|--file-path|--fp|--github|--keyserver|--name|--out|--search|--ssh-identity|--timeout|--type|-dir|-dirseq|-env|-environment|-f|-file|-file-path|-fp|-github|-keyserver|-name|-o|-out|-search|-ssh-identity|-t|-timeout|-type) return 0 ;;
  esac
  return 1
}

_hulak_complete_value() {
  case "$1" in
    --env|--environment|-env|-environment) COMPREPLY=( $(compgen -W "$(_hulak_envs)" -- "$2") ) ;;
    --dir|--dirseq|--file|--file-path|--fp|--out|--ssh-identity|-dir|-dirseq|-f|-file|-file-path|-fp|-o|-out|-ssh-identity) _hulak_path_files "$2" ;;
    *) COMPREPLY=() ;;
  esac
}

_hulak_is_path() {
  case "$1" in
    hulak|hulak:completion|hulak:completion:bash|hulak:completion:zsh|hulak:doctor|hulak:env|hulak:env:add|hulak:env:add-recipient|hulak:env:backup|hulak:env:backup:list|hulak:env:backup:ls|hulak:env:del|hulak:env:delete|hulak:env:edit|hulak:env:export-identity|hulak:env:export-key|hulak:env:g|hulak:env:gen-identity|hulak:env:generate-identity|hulak:env:get|hulak:env:import-identity|hulak:env:import-key|hulak:env:key|hulak:env:keys|hulak:env:l|hulak:env:list|hulak:env:list-identity|hulak:env:list-recipients|hulak:env:ls|hulak:env:migrate|hulak:env:reencrypt|hulak:env:remove|hulak:env:remove-recipient|hulak:env:restore|hulak:env:rm|hulak:env:rotate|hulak:env:rotate-identity|hulak:env:rotate-key|hulak:env:set|hulak:env:show|hulak:env:sync|hulak:env:view|hulak:example|hulak:gql|hulak:graphql|hulak:help|hulak:init|hulak:init:classic|hulak:init:no-vault|hulak:init:plain|hulak:migrate|hulak:run|hulak:secrets|hulak:secrets:add|hulak:secrets:add-recipient|hulak:secrets:backup|hulak:secrets:backup:list|hulak:secrets:backup:ls|hulak:secrets:del|hulak:secrets:delete|hulak:secrets:edit|hulak:secrets:export-identity|hulak:secrets:export-key|hulak:secrets:g|hulak:secrets:gen-identity|hulak:secrets:generate-identity|hulak:secrets:get|hulak:secrets:import-identity|hulak:secrets:import-key|hulak:secrets:key|hulak:secrets:keys|hulak:secrets:l|hulak:secrets:list|hulak:secrets:list-identity|hulak:secrets:list-recipients|hulak:secrets:ls|hulak:secrets:migrate|hulak:secrets:reencrypt|hulak:secrets:remove|hulak:secrets:remove-recipient|hulak:secrets:restore|hulak:secrets:rm|hulak:secrets:rotate|hulak:secrets:rotate-identity|hulak:secrets:rotate-key|hulak:secrets:set|hulak:secrets:show|hulak:secrets:sync|hulak:secrets:view|hulak:version) return 0 ;;
  esac
  return 1
}

_hulak() {
  local cur="${COMP_WORDS[COMP_CWORD]}" prev="${COMP_WORDS[COMP_CWORD-1]}" chain=hulak i=1
  if _hulak_takes_value "$prev"; then _hulak_complete_value "$prev" "$cur"; return; fi
  while (( i < COMP_CWORD )); do
    local w="${COMP_WORDS[i]}"
    if [[ -z $w ]]; then ((i++)); continue; fi
    if [[ $w == -* ]]; then
      _hulak_takes_value "$w" && ((i++))
      ((i++)); continue
    fi
    if _hulak_is_path "$chain:$w"; then chain+=:$w; ((i++)); else break; fi
  done
  case "$chain" in
    hulak)
      COMPREPLY=( $(compgen -W "--debug --dir --dirseq --dry-run --env --environment --file --file-path --fp --help --quiet --show --timeout --version -f -q completion doctor env example gql graphql help init migrate run secrets version" -- "$cur") )
      ;;
    hulak:run)
      if [[ $cur == -* ]]; then COMPREPLY=( $(compgen -W "--debug --dry-run --env --environment --quiet --seq --sequential --show --ssh-identity --timeout -q" -- "$cur") )
      else _hulak_yaml_files "$cur"; fi
      ;;
    hulak:init)
      COMPREPLY=( $(compgen -W "--env --ssh --ssh-identity classic no-vault plain" -- "$cur") )
      ;;
    hulak:init:classic|hulak:init:plain|hulak:init:no-vault)
      COMPREPLY=( $(compgen -W "--env" -- "$cur") )
      ;;
    hulak:example)
      COMPREPLY=( $(compgen -W "--out -o" -- "$cur") )
      ;;
    hulak:doctor)
      COMPREPLY=( $(compgen -W "--fix --json --yes" -- "$cur") )
      ;;
    hulak:gql|hulak:graphql)
      if [[ $cur == -* ]]; then COMPREPLY=( $(compgen -W "--env --environment" -- "$cur") )
      else _hulak_yaml_files "$cur"; fi
      ;;
    hulak:secrets|hulak:env)
      COMPREPLY=( $(compgen -W "add add-recipient backup del delete edit export-identity export-key g gen-identity generate-identity get import-identity import-key key keys l list list-identity list-recipients ls migrate reencrypt remove remove-recipient restore rm rotate rotate-identity rotate-key set show sync view" -- "$cur") )
      ;;
    hulak:secrets:set|hulak:secrets:add|hulak:env:set|hulak:env:add)
      COMPREPLY=( $(compgen -W "--env --environment --stdin --type -t" -- "$cur") )
      ;;
    hulak:secrets:get|hulak:secrets:g|hulak:secrets:show|hulak:secrets:view|hulak:env:get|hulak:env:g|hulak:env:show|hulak:env:view)
      COMPREPLY=( $(compgen -W "--env --environment" -- "$cur") )
      ;;
    hulak:secrets:keys|hulak:secrets:key|hulak:env:keys|hulak:env:key)
      COMPREPLY=( $(compgen -W "--env --environment --search --show" -- "$cur") )
      ;;
    hulak:secrets:delete|hulak:secrets:rm|hulak:secrets:remove|hulak:secrets:del|hulak:env:delete|hulak:env:rm|hulak:env:remove|hulak:env:del)
      COMPREPLY=( $(compgen -W "--env --environment" -- "$cur") )
      ;;
    hulak:secrets:edit|hulak:env:edit)
      COMPREPLY=( $(compgen -W "--env --environment" -- "$cur") )
      ;;
    hulak:secrets:import-key|hulak:secrets:import-identity|hulak:env:import-key|hulak:env:import-identity)
      if [[ $cur == -* ]]; then COMPREPLY=( $(compgen -W "--force --name --stdin" -- "$cur") )
      else _hulak_path_files "$cur"; fi
      ;;
    hulak:secrets:export-key|hulak:secrets:export-identity|hulak:env:export-key|hulak:env:export-identity)
      COMPREPLY=( $(compgen -W "--out -o" -- "$cur") )
      ;;
    hulak:secrets:gen-identity|hulak:secrets:generate-identity|hulak:env:gen-identity|hulak:env:generate-identity)
      COMPREPLY=( $(compgen -W "--name" -- "$cur") )
      ;;
    hulak:secrets:add-recipient|hulak:env:add-recipient)
      COMPREPLY=( $(compgen -W "--allow-rsa --github --keyserver --name --stdin" -- "$cur") )
      ;;
    hulak:secrets:backup|hulak:env:backup)
      COMPREPLY=( $(compgen -W "--force --out -f -o list ls" -- "$cur") )
      ;;
    hulak:secrets:restore|hulak:env:restore)
      if [[ $cur == -* ]]; then COMPREPLY=( $(compgen -W "--force -f" -- "$cur") )
      else _hulak_path_files "$cur"; fi
      ;;
    hulak:completion)
      COMPREPLY=( $(compgen -W "bash zsh" -- "$cur") )
      ;;
    *) COMPREPLY=() ;;
  esac
}

complete -F _hulak hulak
